on:
  push:
    branches:
      - next
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: apt-get install shellcheck
      - name: shellcheck
        run: |
          shellcheck *.sh
          shellcheck lib/*.sh
          shellcheck completions/*.sh
